main: me.scalergames.SuperiorMSG.Main
name: SuperiorMsg
version: 1.0.0
author: ScalerGames
description: A messaging plugin for minecraft. Take control of all messaging!
softdepend: [PlaceholderAPI]
loadbefore: [EssentialsX]
commands:
  sm:
    description: The SuperiorMsg Command
    usage: /<command>
    aliases: [superiormsg, smessage]
  msg:
    description: Private message command
    usage: /<command>
    aliases: [pm, privatemessage, message]
  broadcast:
    description: Broadcast Command
    usage: /<command>
    aliases: [announce]
  broadcastworld:
    description:  A broadcast world command
    usage: /<command>
    aliases: [worldbroadcast, wb, bw]
  localbroadcast:
    description: A local ranged broadcast
    usage: /<command>
    aliases: [broadcastlocal, bl]