main: me.scalergames.SuperiorMSG.Main
name: SuperiorMsg
version: 1.0.0
author: ScalerGames
description: A messaging plugin for minecraft. Take control of all messaging!
softdepend: [PlaceholderAPI]
loadbefore: [EssentialsX]
commands:
  sm:
  msg:
  broadcast:
  broadcastworld:
  localbroadcast: